---
title: "Bitcoin Neural Network Forecasting"
author: "Ian"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    number_sections: no
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: yes
      smooth_scroll: no
editor_options:
  chunk_output_type: inline
---

# 1. Load Packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = FALSE,
  comment = "#",
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  fig.align = "center",
  class.source = 'white',
  options(scipen=999) # suppress scientific notation
)
```

```{r load libraries}
library(tidyverse)  # Data manipulation
library(tidymodels) # Building machine learning workflows and models
library(keras)      # neural networks
```

```{r set dates}
# Set dates for this project. YMD Format.
sDate = "2018-01-01"
eDate = "2020-11-30"
```


# 2. Extracting Data/Adding features

## 2.1 Getting Bitcoin Prices
```{r import Bitcoin prices}
# Read Data
bitcoin_price <- read_csv("../data/bitcoin_price.csv")

# Cleaning
bitcoin_price[bitcoin_price == 0] <- NA
bitcoin_price <- bitcoin_price %>%
  map_df(na.locf)

# Defining Target
bitcoin_model <- bitcoin_price %>%
  select(date, close, volume_btc, volume_currency) %>% 
  tq_mutate(select = close,
            mutate_fun = periodReturn,
            period = 'daily',
            type = 'arithmetic',
            col_rename = 'future_return') %>%
  mutate(future_return_sign = as.factor(ifelse(future_return > 0, 1, 0))) %>% 
  # Shift up future_returns and sign by 1. Use today's data to predict tomorrow's returns.
  # future_returns indicates the returns if I buy at today's close and sell at tmrrw's close
  # each row represent today
  mutate_at(c("future_return", "future_return_sign"), lead)
bitcoin_model <- bitcoin_model[-nrow(bitcoin_model), ]

rmarkdown::paged_table(bitcoin_model %>% head())
```

## 2.2 Getting Bitcoin Features

```{r import Bitcoin features}
# Importing features from Marcus
bitcoin_features <- read_csv("../data/bitcoin_features.csv")
bitcoin_features <- bitcoin_features[-nrow(bitcoin_features), ]  # Remove latest date to match bitcoin prices and future returns

rmarkdown::paged_table(bitcoin_features %>% head())
```

## 2.3 Merge all data into 1 tibble

```{r merge price with features}
# Combine price data with features
bitcoin_model <- bitcoin_model %>%
  left_join(bitcoin_features, by="date")

rmarkdown::paged_table(bitcoin_model %>% head())
```

## 2.4 Train/Test Data Split

```{r train test split}
set.seed(123)
# YMD format
train <- bitcoin_model %>% filter(between(date, as.Date("2018-01-01"), as.Date("2019-12-31")))
validate <- bitcoin_model %>% filter(between(date, as.Date("2020-01-01"), as.Date("2020-06-30")))
test <- bitcoin_model %>% filter(between(date, as.Date("2020-07-01"), as.Date("2020-11-29")))
```


# 3. Single Hidden Layer Neural Network

Source: [Tidymodels - Classification Models Using a Neural Network](https://www.tidymodels.org/learn/models/parsnip-nnet/)

## 3.1 Fitting the Neural Network

```{r single hidden layer}
bitcoin_rec <- 
  recipe(future_return_sign ~ ., data = train) %>%
  # feature engineering for date
  step_date(date, features = c("dow", "month")) %>% 
  step_rm(date) %>%
  # transform predictors to be more symmetric
  step_BoxCox(all_numeric()) %>%
  # convert predictors to common scale
  step_normalize(all_numeric()) %>%
  prep(training = train, retain = TRUE)
  
# We will juice() to get the processed training set back

# For validation:
val_normalized <- bake(bitcoin_rec, new_data = validate, all_predictors())
# For testing when we arrive at a final model: 
test_normalized <- bake(bitcoin_rec, new_data = test, all_predictors())

set.seed(123)

nnet_fit <-
  mlp(epochs = 100, hidden_units = 5, dropout = 0.1) %>%
  set_mode("classification") %>% 
  # Also set engine-specific `verbose` argument to prevent logging the results: 
  set_engine("keras", verbose = 0) %>%
  fit(future_return_sign ~ ., data = juice(bitcoin_rec))

nnet_fit
```

# 3.2 Neural Network Model Performance

